Algoritmo "Exercicio09ManzanoLacopara"
// Disciplina  : [Linguagem e Lógica de Programação com Java Script]
// Professor   : Jailson Costa Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme de Moura Garoli
// Data atual  : 02/05/2022
Var
   // Seção de Declarações das variáveis
   contadora,acumuladora,troca:inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
     acumuladora<-1
     Escreval(acumuladora)
   para contadora de 0 ate 15 passo 1 faca
      anterior<-acumuladora+acumuladora
      acumuladora<-contadora+anterior
      Escreval(anterior)

   fimpara


Fimalgoritmo
