Algoritmo "Exercicio12Faccat"
// Disciplina  :[Linguagem e Lógica de Programação]
// Professor   : Jailson Costa Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme Garoli
// Data atual  : 31/03/2022
Var
// Seção de Declarações das variáveis 
celsius,fahrenheit:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite a temperatura em graus Fahrenheit :")
Leia(fahrenheit)
celsius<-(5*fahrenheit-160)/9
Escreval("A temperatura em graus celsius é :" ,celsius)
Fimalgoritmo