Algoritmo "Exercicio15Faccat"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa Santos
// Descrição   :
// Autor(a)    : Guilherme Garoli
// Data atual  : 04/04/2022
Var
// Seção de Declarações das variáveis 
numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um número")
leia(numero)
  se numero>=0 entao
 Escreval("É positivo")
  senao
 Escreval("É negativo")
  fimse
Fimalgoritmo