Algoritmo "ExercicioDesejaContinuar"
// Disciplina  : [Linguagem e Lógica de Programação com Java Script]
// Professor   : Jailson Costa Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme de Moura Garoli
// Data atual  : 25/04/2022
Var
   // Seção de Declarações das variáveis
   numero:inteiro
   multiplicacao:inteiro
   resposta:caracter
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   resposta<-"sim"
   enquanto resposta = "sim" faca
      Escreval("Digite um valor:")
      Leia(numero)
      multiplicacao<-numero*3
      Escreval("O valor da multiplicação é :" ,multiplicacao)
      Escreval("Deseja efetuar outro calculo ?")
      Leia(resposta)
      limpatela
    fimenquanto

Fimalgoritmo