Algoritmo "ExercicioDesvioCondicionalSimples"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme
// Data atual  : 31/03/2022
Var
// Seção de Declarações das variáveis 
valor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um valor")
Leia(valor)
se valor<10 entao
Escreval("Valor digitado é menor que 10")


Fimalgoritmo
