Algoritmo "Exercicio19Faccat"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa Santos
// Descrição   :
// Autor(a)    : Guilherme Garoli
// Data atual  : 04/04/2022
Var
   // Seção de Declarações das variáveis
   numero1,numero2:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
  Escreval("Digite um número")
  leia(numero1)
  Escreval("Digite um número")
  leia(numero2)
  se numero1>numero2 entao
  Escreval("O numero 1 é maior que o número 2")
  senao
  Escreval("O numero 2 é maior que o número 1")
  fimse
Fimalgoritmo