Algoritmo "Exercicio14Faccat"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa Santos
// Descrição   : É maior que 10/É menor que 10
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/04/2022
Var
// Seção de Declarações das variáveis 
numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreval("Dgite um numero :")
 Leia(numero)
 se numero>10 entao
  Escreval("É maior que 10")
 senao
  Escreval("É menor que 10")
 fimse
 Fimalgoritmo