Algoritmo "Retangulo"
// Disciplina  : [Linguagem e Lógica de Programação com Javascrip]
// Professor   : Jailson Costa Santos
// Descrição   : Exercicio 6
// Autor(a)    : Guilherme
// Data atual  : 28/03/2022
Var
// Seção de Declarações das variáveis 
base:real
altura:real
area:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite a base: ")
Leia(base)
Escreval("Digite a altura: ")
Leia(altura)
area<-base*altura/2
Escreval("o sucessor do número digitado é :" ,area)//Saída de dados
Fimalgoritmo