Algoritmo "Sucessor"
// Disciplina  : [Linguagem e Lógica de Programação com Javascrip]
// Professor   : Jailson Costa Santos
// Descrição   : Exercicio 5
// Autor(a)    : Guilherme
// Data atual  : 28/03/2022
Var
// Seção de Declarações das variáveis 
numero:inteiro
sucessor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um número: ")
Leia (numero)
sucessor<-numero+1
Escreval("o sucessor do número digitado é :" ,sucessor)//Saída de dados
Fimalgoritmo